# Generated by Django 6.1.1 on 2026-09-28 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_product_image_productimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['id'], 'verbose_name': 'Изображение товара', 'verbose_name_plural': 'Галерея изображений'},
        ),
        migrations.AddField(
            model_name='product',
            name='is_on_order',
            field=models.BooleanField(default=False, verbose_name='Под заказ'),
        ),
    ]
