# Generated by Django 6.1.1 on 2026-10-01 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_productimage_options_product_is_on_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Изображение (плитка в каталоге)'),
        ),
    ]
